### ISSUE TITLE
CKEditor

### ISSUE THREAD

**Issue by serkaniyigun** [karthik25/sblog.net#3]
Uncaught TypeError: Cannot read property 'textColorTitle' of undefined ckeditor.js:47

**Comment by karthik25** [comment]
@serkaniyigun - Thank you for reporting this issue! I found out the reason - CKEditor has a lang folder (https://github.com/karthik25/sblog.net/tree/master/sBlog.Net/Content/CKEditor/lang) which currently only contains "en.js". Since your browser culture is not "en-us", this seems to be happening. Once the remaining language js files are added, this error will go away! I will check them in once I go back from work. 

For now here is the link for full CKEditor source [http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.2/ckeditor_3.6.2.zip]. Once the contents of ckeditor_3.6.2.zip\ckeditor\lang are added to sBlog.Net\Content\CKEditor\lang this error should go away (_languages.js should also be replaced) ! I will be checking in this later today so that you can update using your upstream to sBlog.Net!

**Comment by serkaniyigun** [comment]
@karthik25 - i downloaded CKEditor last version and replacing lang folder. and still error. but replacing ckeditor.js and lang folder. it fixing problem. and yep this error language js file error

**Comment by karthik25** [comment]
@serkaniyigun - You also had to replace ckeditor.js? Probably because of the version change, there could be a dependency on the _languages.js file. I will check that out too while checking in the new files to the "lang" folder! Thanks for your inputs and hope you enjoy sBlog.Net!

**Comment by karthik25** [comment]
Fixed in the master and the sblog.net 2.0 branch
